stages:
  - test
  - build
  - deploy


variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}
  NAMESPACE: hosting

.docker-login: &docker-login
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}

build:
  services:
  image: docker:latest
  stage: test
  tags:
    - build
  script:
    - docker build -t ${CONTAINER_IMAGE}:${CI_COMMIT_SHA:0:8} .
    - docker rmi --force ${CONTAINER_IMAGE}:${CI_COMMIT_SHA:0:8}
  except:
    - develop
    - master
    - staging
    - tags


build:
  image: docker:latest
  stage: build
  tags:
    - build
  <<: *docker-login
  script:
    - docker build -t ${CONTAINER_IMAGE}:${CI_COMMIT_SHA:0:8} .
    - docker push ${CONTAINER_IMAGE}:${CI_COMMIT_SHA:0:8}
    - docker rmi --force ${CONTAINER_IMAGE}:${CI_COMMIT_SHA:0:8}
  only:
    - develop


deploy:
  image: exon/helm
  stage: deploy
  tags:
    - develop
  before_script:
    - mkdir -p /etc/deploy/
    - echo ${SANDBOX_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - helm init --client-only
    - helm repo update
  environment:
    name: develop
  script:
    - cd deploy
    - helm upgrade --install ${CI_PROJECT_NAME} --namespace=${NAMESPACE} --set image.tag=${CI_COMMIT_SHA:0:8} --values values.yaml --values env/develop.yaml .
  only:
    - develop
