[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/go-pg/migrations"
  version = "~6.2.0"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "~6.11.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.5"
