required = [
  "git.containerum.net/ch/auth",
  "github.com/containerum/kube-client",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "github.com/containerum/utils"
    non-go = false

  [[prune.project]]
    name = "git.containerum.net/ch/auth"
    non-go = false

  [[prune.project]]
    name = "github.com/containerum/cherry"
    non-go = false

  [[prune.project]]
    name = "github.com/containerum/kube-client"
    non-go = false

[[constraint]]
  name = "github.com/go-pg/migrations"
  version = "~6.2.0"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "~6.13.5"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.5"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "~1.2.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "~9.12.0"

[[constraint]]
  name = "github.com/go-playground/universal-translator"
  version = "~0.16.0"

[[constraint]]
  name = "github.com/containerum/utils"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/go-playground/locales"
  version = "~0.12.1"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "~1.6.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "~1.2.0"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/auth"

[[constraint]]
  name = "github.com/containerum/cherry"
  version = "~1.0.1"

[[constraint]]
  name = "github.com/containerum/bill-external"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/containerum/kube-client"
  version = "~0.23.2"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/volume-manager"