swagger: "3.0"
definitions:
  AccessLevel:
    type: string
    enum:
      - none
      - read
      - readdelete
      - write
      - owner
  AccessObject:
    type: object
    properties:
      access:
        $ref: '#/definitions/AccessLevel'
      id:
        type: string
        format: uuid
      label:
        type: string
  ResourceAccesses:
    type: object
    properties:
      namespace:
        type: array
        items:
          $ref: '#/definitions/AccessObject'
      volume:
        type: array
        items:
          $ref: '#/definitions/AccessObject'
parameters:
  SubstitutedUserID:
    $ref: "vendor/git.containerum.net/ch/utils/httputil/swagger.json#/parameters/SubstitutedUserID"
  UserIDHeader:
    $ref: "vendor/git.containerum.net/ch/api-gateway/pkg/utils/headers/swagger.json#/parameters/UserIDHeader"
  UserRoleHeader:
    $ref: "vendor/git.containerum.net/ch/api-gateway/pkg/utils/headers/swagger.json#/parameters/UserRoleHeader"