swagger: "3.0"
definitions:
  AccessLevel:
    type: string
    enum:
      - none
      - read
      - readdelete
      - write
      - owner
  ResourcesAccesses:
    $ref: "vendor/git.containerum.net/ch/auth/swagger.json#/definitions/ResourcesAccess"
parameters:
  SubstitutedUserID:
    $ref: "vendor/github.com/containerum/utils/httputil/swagger.json#/parameters/SubstitutedUserID"
  UserIDHeader:
    $ref: "vendor/github.com/containerum/api-gateway/pkg/utils/headers/swagger.json#/parameters/UserIDHeader"
  UserRoleHeader:
    $ref: "vendor/github.com/containerum/api-gateway/pkg/utils/headers/swagger.json#/parameters/UserRoleHeader"
responses:
  error:
    description: cherry error
    schema:
      $ref: "vendor/github.com/containerum/cherry/swagger.json#/definitions/Err"