{{- if .Values.env.local.DB_PASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.env.local.DB_PASSWORD }}
  pg-password: {{ .Values.env.local.DB_PASSWORD | b64enc }}
  {{- end }}
{{- end }}
