tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/permissions
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 4242
  targetPort: 4242
  externalIP:

env:
  global:
    MODE: "release"
    LOG_LEVEL: 4
    LISTEN_ADDR: ":4242"
    DB_BASE: "permissions"
    DB_USER: "permissions"
    DB_SSLMODE: "false"
  local:
    DB_HOST: "postgres-master.postgres.svc:5432"
    AUTH_ADDR: "auth:1112"
    USER_ADDR: "user-manager:8111"
    KUBE_API_ADDR: "kube:1214"
    RESOURCE_SERVICE_ADDR: "resource:1213"
    BILLING_ADDR: "billing-manager:5005"
    VOLUME_MANAGER_ADDR: "volume:4343"
    DB_PASSWORD:
    SOLUTIONS_ADDR: "solutions:6767"

postgresql:
  persistence:
    enabled: false
  postgresDatabase: permissions
  # postgresUser: postgres
  # postgresPassword: password
